@startuml
'https://plantuml.com/class-diagram

hide circle
top to bottom direction
skinparam linetype ortho
title Domain Model Diagram

    class User {
        - name : String
        - adress : String
        - phone_number : String
        - email : String
    }

    class Music {
        - name: String
        - publication_date : Date
        - duration : timestamp
    }

    class Artist {
        - name : String
        - birthdate : Date
        - sex : String
    }

    class Playlist {
         - name : String
         - createdby : String
         - totalduration : float
    }

     class Album {
          - name : String
          - name : String
          - lauchdate : Date
     }

    class Review {
        - pontuation : int
        - description : String
    }

    class User_playlist {
         - name : String
         - name : String
    }

    User "1" o-- "*" Playlist
    User "*" o-- "*" Playlist
    Artist "1" o-- "*" Music
    Music "*" o-- "1" Artist
    Playlist "*" o-- "*" Music
    User "1" o-- "*" Review
    Review "*" o-- "1" Music
    Album "1" o-- "*" Music
    Artist "1" o-- "*" Album