@startuml
'https://plantuml.com/class-diagram

hide circle
top to bottom direction
skinparam linetype ortho
title Domain Model Diagram

    class User {
        - name : String
        - adress : String
        - phone_number : String
        - email : String
    }

    class Music {
        - name: String
        - publication_date : Date
        - duration : timestamp
    }

    class Artist {
        - name : String
        - birthdate : Date
        - sex : String
    }

    class Playlist {
         - name : String
         - createdby : String
         - totalduration : float
    }

    class Review {
        - pontuation : int
        - description : String
    }


    Playlist "*" o-- "1" User
    Review "*" o-- "1" Music



