@startuml
'https://plantuml.com/use-case-diagram
left to right direction
title Use Case Diagram


actor "User" as User

usecase "View Playlists" as UC1
usecase "Create Playlist" as UC2
usecase "Delete Playlist" as UC3
usecase "View Playlist Details" as UC4
usecase "Add Music to Playlist" as UC5
usecase "Remove Music from Playlist" as UC6
 usecase "Search Music" as UC7
 usecase "Recognize Music" as UC8

User -- UC1
User -- UC2
User -- UC3
User -- UC4
User -- UC5
User -- UC6
User -- UC7
User -- UC8
 @enduml