@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "System" as System

User -> System: Search for the music
System --> User: Show music options
User -> System: Select to add to playlist
System --> User: Add to playlist

@enduml