@startuml
'https://plantuml.com/use-case-diagram
left to right direction
title Use Case Diagram

actor "User" as umain
rectangle "Main Screen" {
    usecase "1. Identify a Song" as UCMS1
    usecase "2. Search Music by Name" as UCMS2
    usecase "3. Search Artist by Name" as UCMS3
    usecase "4. Browse Albums" as UCMS4
    usecase "5. Go through nav bar buttons" as UCMS5
}
umain --> UCMS1
umain --> UCMS2
umain --> UCMS3
umain --> UCMS4
umain --> UCMS5

newpage
left to right direction
title Use Case Diagram
actor "User" as ups
rectangle "Playlist Screen" {
    usecase "1. Create Playlist" as UCPS1
    usecase "2. Add Music to Playlist" as UCPS2
    usecase "3. Remove Music from Playlist" as UCPS3
    usecase "4. View Your Playlists" as UCPS4
    usecase "5. Go through nav bar buttons" as UCPS5
}
ups --> UCPS1
ups --> UCPS2
ups --> UCPS3
ups --> UCPS4
ups --> UCPS5

newpage
left to right direction
title Use Case Diagram


actor "User" as uds
rectangle "Music/Album/Artist Details" {
    usecase "1. See Music Details" as UCDS1
    usecase "2. See Album Details" as UCDS2
    usecase "3. See Artist Details" as UCDS3
    usecase "4. Read Reviews" as UCDS4
    usecase "5. Write Review" as UCDS5
    usecase "6. Go through search bar" as UCDS6
}
uds --> UCDS1
uds --> UCDS2
uds --> UCDS3
uds --> UCDS4
uds --> UCDS5
uds --> UCDS6

newpage
left to right direction
title Use Case Diagram

actor "User" as uss
rectangle "Settings Screen" {
    usecase "1. Change Profile Settings" as UCSS1
    usecase "2. Change App Theme (Light/Dark)" as UCSS2
}
uss --> UCSS1
uss --> UCSS2

@enduml